# Generated by Django 3.0.5 on 2020-04-18 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_auto_20200418_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='contract',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 4, 18, 22, 30, 34, 513719)),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='phone',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='site',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_type',
            field=models.TextField(default=''),
        ),
    ]
