# Generated by Django 3.0.5 on 2020-04-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_auto_20200419_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='conformity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='vacancy',
            field=models.TextField(default=''),
        ),
    ]
