# Generated by Django 3.0.5 on 2020-04-19 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_auto_20200419_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='skills',
            new_name='skills_text',
        ),
    ]
