# Generated by Django 3.0.5 on 2020-04-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0009_auto_20200419_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='conformity',
            field=models.IntegerField(default=0),
        ),
    ]
