# Generated by Django 3.0.5 on 2020-04-19 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0011_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='skills_text',
            new_name='skills',
        ),
    ]
