# Generated by Django 3.0.5 on 2020-04-26 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0013_auto_20200419_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='related_request',
            field=models.ManyToManyField(to='scraping.Request'),
        ),
        migrations.AddField(
            model_name='employee',
            name='related_vacancy',
            field=models.ManyToManyField(to='scraping.Job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 4, 26)),
        ),
    ]
