# Generated by Django 3.0.5 on 2020-05-03 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0015_auto_20200503_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 5, 3)),
        ),
    ]
