# Generated by Django 3.0.5 on 2020-05-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skill_learn_materials'),
        ('scraping', '0016_auto_20200503_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(to='skills.Skill'),
        ),
    ]
