# Generated by Django 3.0.5 on 2020-05-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0018_remove_employee_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
