# Generated by Django 3.0.5 on 2020-05-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skills.Skill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='aliases',
            field=models.TextField(default=''),
        ),
    ]
