# Generated by Django 3.0.5 on 2020-05-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20200503_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='learn_materials',
            field=models.BooleanField(default=False),
        ),
    ]
