# Generated by Django 3.0.5 on 2020-05-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skill_learn_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='aliases',
            field=models.TextField(blank=True, null=True),
        ),
    ]
